const CartActionTypes = {
<<<<<<< HEAD
   SELECT_ATTRIBUTE:"SELECT_ATTRIBUTE",
   TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
   ADD_ITEM: "ADD_ITEM",
   REMOVE_ITEM: "REMOVE_ITEM",
   CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
=======
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
>>>>>>> 112475a44e996aa173e44b3766e572889e39c17e
};

export default CartActionTypes;
